services:
    websocket:
        build:
            context: ./websocket
            dockerfile: Dockerfile
        image: websocket
        pull_policy: never
        container_name: websocket
        tty: true
        ports:
             - "3000:3000"
        volumes:
             - websocket:/home/node/zoom
        restart: on-failure

volumes:
    websocket:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${NODE_VOLUME_PATH}